[gcloud]
disabled = true

[directory]
truncation_length = 8   # 0 = shows the full path (Disable truncation)
truncate_to_repo = false # false = always show full path, not just from the git repo root
style = "bold cyan"      # Optional: Makes the path color stand out

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
